---
# tasks file for ansible-role-rutorrent


- name: check for current installation
  stat: "path={{ rutorrent_dir_install }}/conf"
  register: rutorrent_conf


- include: setup.yml
  when: not rutorrent_conf.stat.exists


- include: configuration.yml
