# ansible-role-rutorrent/tasks/main.yml
---
- name: check for current installation
  stat: "path={{ rutorrent_dir_install }}/conf"
  register: rutorrent_conf

# -------------
# Install rutorrent
# -------------
- name: "all | ensure install directory exists"
  file: path="{{ rutorrent_dir_install }}" state=directory
  when: not rutorrent_conf.stat.exists

- name: "all | clone rutorrent repo"
  git: 
    repo: "{{ rutorrent_repo }}" 
    dest: "{{ rutorrent_dir_install }}" 
    version: "{{ rutorrent_version }}" 
    update: "{{ rutorrent_force_udpate }}"

# -------------
# Config rutorrent
# -------------
- name: "all | ensure we have bin locations set by template"
  template: src="config.php.j2" dest="{{ rutorrent_dir_install }}/conf/config.php"

- name: "all | ensure www-data/nginx owns all files in install directory"
  file:
    path: "{{ rutorrent_dir_install }}"
    state: directory
    group: "{{ rutorrent_dir_install_group }}"
    owner: "{{ rutorrent_dir_install_owner }}"
    recurse: Yes
...
